name: CineViet
options:
  bundleIdPrefix: live.cineviet
  deploymentTarget:
    iOS: "16.0"
packages:
  SocketIO:
    url: https://github.com/socketio/socket.io-client-swift
    from: 16.1.0
  GoogleSignIn:
    url: https://github.com/google/GoogleSignIn-iOS
    from: 8.0.0
settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_BUNDLE_IDENTIFIER: live.cineviet.cinevietios
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  CineViet:
    type: application
    platform: iOS
    sources:
      - path: CineViet
    dependencies:
      - package: SocketIO
      - package: GoogleSignIn
        product: GoogleSignIn
    info:
      path: CineViet/Resources/Info.plist
      properties:
        CFBundleDisplayName: CineViet
        CFBundleURLTypes:
          - CFBundleTypeRole: Editor
            CFBundleURLSchemes:
              - com.googleusercontent.apps.186784861581-mc6buqlfpbrprko3iqfp6fi0biqc3o3s
        GIDClientID: 186784861581-mc6buqlfpbrprko3iqfp6fi0biqc3o3s.apps.googleusercontent.com
        NSCameraUsageDescription: Dùng camera để quét mã QR đăng nhập TV.
        UILaunchScreen: {}
        UIBackgroundModes:
          - audio
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: "YES"
    scheme:
      testTargets: []
