name: CineViet
options:
  bundleIdPrefix: live.cineviet
  deploymentTarget:
    iOS: "16.0"
settings:
  base:
    SWIFT_VERSION: "5.9"
    PRODUCT_BUNDLE_IDENTIFIER: live.cineviet.ios
    TARGETED_DEVICE_FAMILY: "1,2"
targets:
  CineViet:
    type: application
    platform: iOS
    sources:
      - path: CineViet
    settings:
      base:
        GENERATE_INFOPLIST_FILE: "YES"
        INFOPLIST_KEY_CFBundleDisplayName: CineViet
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIBackgroundModes: audio
        INFOPLIST_KEY_UIUserInterfaceStyle: Dark
        SWIFT_EMIT_LOC_STRINGS: "YES"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
    scheme:
      testTargets: []
